### PR TITLE
https://github.com/kpelykh/docker-java/issues/31

### PR DESCRIPTION
**Pull request by marcuslinke**

### CODE REVIEW

**Comment by marcuslinke** [comment]
It would be great to have a new release with it. I need the nocache option for https://github.com/jenkinsci/docker-build-step-plugin

Thanks!

**Comment by marcuslinke** [comment]
Thanks for merging! Any chance to get a new release that includes this fix?

**Comment by kpelykh** [comment]
@marcuslinke Do you need release or snapshot build will work?

**Comment by marcuslinke** [comment]
@kpelykh Unfortunally the jenkins project doesn't allow external SNAPSHOT dependencies when creating a pull request for a jenkins plugin. So a release would be really fine. Thanks in advance!

**Pull request merged**
