### PR TITLE
Upgraded from jersey-json to jackson-jaxrs 2.3.3

### PR DESCRIPTION
**Pull request by rferreira**
Hi there, please approve the pull request below, it ditches jersey-json in favor of the latest jackson-jaxrs package making it easier to integrate docker-java with new applications. This addresses bug #46,

### CODE REVIEW

**Comment by rferreira** [comment]
Bump... have you had a chance to review this patch?

**Comment by marcuslinke** [comment]
@rferreira Whats the problem with jersey-json? Whats the benefit of using jackson-jaxrs? Could you explain please? Thanks.

**Comment by rferreira** [comment]
that version of jersey-json is on a much older version of jackson (1.x) that causes issues since jackson has changed it's package names from org.codehaus.jackson to com.fasterxml.jackson (in the 2.x series). More importantly, if you are working on a new codebase that already uses com.fasterxml you end up having dependencies problems (specially if you are trying to bundle deps in some sort of ubber jar mode), for example using docker-java with dropwizard. Eventually, we need to look into upgrading docker-java to a newer version of jersey as well.

**Comment by marcuslinke** [comment]
I've integrated your changes in my branch https://github.com/marcuslinke/docker-java/tree/jackson-jaxrs-2.3.3. Could you please check if this is working for you? Anyway i will close this pull request in favor of the new one.

**Comment by rferreira** [comment]
@marcuslinke it looks good to me!

**Pull request closed without merging**
